---
- name: Настройка self-hosted среды разработки (без GUI)
  hosts: localhost
  become: true
  vars:
    dev_user: "dev"
    code_server_version: "4.98.1"  # актуальная версия
    forgejo_version: "14.0.1"
    arch: "amd64"

  tasks:
    # 1. Создать пользователя dev (для работы в code-server)
    - name: Создать пользователя dev
      user:
        name: "{{ dev_user }}"
        shell: /bin/bash
        create_home: yes
        groups: sudo
        append: yes

    # 2. Установить зависимости
    - name: Установить базовые пакеты
      apt:
        name:
          - curl
          - wget
          - ca-certificates
          - xz-utils
          - sqlite3
          - ufw
        state: present
        update_cache: yes

    # 3. Установить code-server (VSCodium в браузере)
    - name: Скачать и установить code-server
      shell: |
        curl -fsSL https://code-server.dev/install.sh | sh -s -- --method=standalone --prefix=/usr/local --version {{ code_server_version }}
      args:
        creates: /usr/local/bin/code-server

    - name: Создать конфиг code-server
      file:
        path: "/home/{{ dev_user }}/.config/code-server"
        state: directory
        owner: "{{ dev_user }}"
        group: "{{ dev_user }}"
        mode: '0700'

    - name: Настроить code-server (доступ из локальной сети)
      copy:
        content: |
          bind-addr: 0.0.0.0:8080
          auth: password
          password: "{{ lookup('password', '/dev/null length=24 chars=ascii_letters,digits') }}"
          cert: false
        dest: "/home/{{ dev_user }}/.config/code-server/config.yaml"
        owner: "{{ dev_user }}"
        group: "{{ dev_user }}"
        mode: '0600'

    - name: Создать systemd-юнит для code-server
      template:
        src: code-server.service.j2
        dest: "/etc/systemd/system/code-server@{{ dev_user }}.service"
        mode: '0644'

    - name: Запустить code-server
      systemd:
        name: "code-server@{{ dev_user }}"
        enabled: yes
        state: started
        daemon_reload: yes

    # 4. Установить Forgejo
    - name: Скачать Forgejo
      get_url:
        url: "https://codeberg.org/forgejo/forgejo/releases/download/v{{ forgejo_version }}/forgejo-{{ forgejo_version }}-linux-{{ arch }}.xz"
        dest: "/tmp/forgejo.xz"
        mode: '0644'

    - name: Распаковать Forgejo
      shell: xz --decompress --stdout /tmp/forgejo.xz > /usr/local/bin/forgejo
      args:
        creates: /usr/local/bin/forgejo

    - name: Сделать исполняемым
      file:
        path: /usr/local/bin/forgejo
        mode: '0755'

    - name: Создать пользователя forgejo
      user:
        name: forgejo
        system: yes
        shell: /usr/sbin/nologin
        home: /var/lib/forgejo
        create_home: yes

    - name: Создать каталоги Forgejo
      file:
        path: "{{ item }}"
        state: directory
        owner: forgejo
        group: forgejo
        mode: '0750'
      loop:
        - /etc/forgejo
        - /var/lib/forgejo

    - name: Создать конфиг Forgejo (SQLite)
      copy:
        content: |
          [database]
          DB_TYPE = sqlite3
          PATH = /var/lib/forgejo/gitea.db

          [repository]
          ROOT = /var/lib/forgejo/repositories

          [server]
          HTTP_PORT = 3000
          DOMAIN = localhost
          ROOT_URL = http://localhost:3000/
          HTTP_ADDR = 0.0.0.0  # ← разрешить LAN

          [security]
          INSTALL_LOCK = false
          SECRET_KEY = {{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}

          [service]
          DISABLE_REGISTRATION = false
        dest: /etc/forgejo/app.ini
        owner: forgejo
        group: forgejo
        mode: '0640'

    - name: Создать systemd-юнит Forgejo
      copy:
        content: |
          [Unit]
          Description=Forgejo
          After=network.target

          [Service]
          Type=simple
          User=forgejo
          WorkingDirectory=/var/lib/forgejo
          ExecStart=/usr/local/bin/forgejo web --config /etc/forgejo/app.ini
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/forgejo.service
        mode: '0644'

    - name: Запустить Forgejo
      systemd:
        name: forgejo
        enabled: yes
        state: started
        daemon_reload: yes

    # 5. Настроить файрвол (только LAN)
    - name: Разрешить порты в LAN
      shell: |
        ufw allow from 192.168.0.0/16 to any port 8080
        ufw allow from 192.168.0.0/16 to any port 3000
        ufw --force enable

    # 6. Вывести инструкцию
    - name: Инструкция по использованию
      debug:
        msg:
          - "✅ Готово!"
          - "• code-server (VSCodium в браузере): http://<IP_вашего_ноутбука>:8080"
          - "• Forgejo (Git-сервер): http://<IP_вашего_ноутбука>:3000"
          - "• Пароль от code-server сохранён в /home/dev/.config/code-server/config.yaml"
          - "• Доступ только из локальной сети (192.168.0.0/16)"